AiXinYaoYeV2/Controllers/BonusProductController.cs
using System.Linq;
using AiXinYaoYeV2.Database;
using Microsoft.AspNetCore.Mvc;

namespace AiXinYaoYeV2.Controllers
{
    public class BonusProductController:Controller
    {
        private MyDbContext db;

        public BonusProductController(MyDbContext db)
        {
            this.db = db;
        }

        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        public ActionResult List() {
            var bonusProducts = db.BonusProducts.ToList();
            return View(bonusProducts);
        }

        /// <summary>
        /// 详情
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Detail(int id)
        {
            var bonusProduct = db.BonusProducts.FirstOrDefault(a => a.Id == id);
            return View(bonusProduct);
        }
    }
}

AiXinYaoYeV2/Controllers/RecommendProductController.cs
using System.Linq;
using AiXinYaoYeV2.Database;
using Microsoft.AspNetCore.Mvc;

namespace AiXinYaoYeV2.Controllers
{
    public class RecommendProductController : Controller
    {
        private MyDbContext db;

        public RecommendProductController(MyDbContext db)
        {
            this.db = db;
        }

        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            var recommandProducts = db.RecommandProducts.ToList();
            return View(recommandProducts);
        }

        /// <summary>
        /// 详情
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Detail(int id)
        {
            var recommandProduct = db.RecommandProducts.FirstOrDefault(a => a.Id == id);
            return View(recommandProduct);
        }
    }
}

AiXinYaoYeV2/Areas/Admin/Views/Shared/_Layout.cshtml
@using AiXinYaoYeV2.Areas.Admin.Controllers
<!DOCTYPE html>
<html style="height: auto; min-height: 100%;">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>爱心药业管理后台</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="alternate icon" type="image/jpeg" href="~/image/favicon.jpg">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Theme style -->
    <link href="https://cdn.bootcss.com/admin-lte/2.4.2/css/AdminLTE.min.css" rel="stylesheet">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect. -->
    <link href="https://cdn.bootcss.com/admin-lte/2.4.2/css/skins/skin-red.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @RenderSection("style", false)
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-red sidebar-mini" style="height: auto; min-height: 100%;">
    <div class="wrapper" style="height: auto; min-height: 100%;">

        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini" style="height: 100%"><img src="~/image/favicon.jpg" style="height: 100%; object-fit: contain;" /></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg" style="height: 100%"><img src="~/image/favicon.jpg" style="height: 100%; object-fit: contain;"/></span>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="@Url.Action("Logout","Login")"><i class="fa fa-user-times">&nbsp;登出</i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">

            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">

                <!-- Sidebar Menu -->
                <ul class="sidebar-menu tree" data-widget="tree">
                    <li class="header"></li>
                    <!-- Optionally, you can add icons to the links -->
                    <li class="@(this.ViewContext.RouteData.Values["controller"].ToString() == nameof(BonusProductController)?"active":"")"><a href="@Url.Action("Index","BonusProduct")"><i class="fa fa-product-hunt"></i> <span>积分商品</span></a></li>
                    <li class="@(this.ViewContext.RouteData.Values["controller"].ToString()  == nameof( RecommendProductController)?"active":"")"><a href="@Url.Action("Index","RecommendProduct")"><i class="fa fa-fire"></i> <span>推荐商品</span></a></li>
                </ul>
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="min-height: 858px;">
            <div style="padding: 20px 30px; background: rgb(243, 156, 18); z-index: 999999; font-size: 16px; font-weight: 600; display: none;"><a class="pull-right" href="#" data-toggle="tooltip" data-placement="left" title="Never show me this again!" style="color: rgb(255, 255, 255); font-size: 20px;">×</a><a href="https://themequarry.com" style="color: rgba(255, 255, 255, 0.9); display: inline-block; margin-right: 10px; text-decoration: none;">Ready to sell your theme? Submit your theme to our new marketplace now and let over 200k visitors see it!</a><a class="btn btn-default btn-sm" href="https://themequarry.com" style="margin-top: -5px; border: 0px; box-shadow: none; color: rgb(243, 156, 18); font-weight: 600; background: rgb(255, 255, 255);">Let's Do It!</a></div>

            <!-- Main content -->
            <section class="content container-fluid" style="overflow-x: auto;">

                <!--------------------------
                  | Your Page Content Here |
                  -------------------------->

                @RenderBody()

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="pull-right hidden-xs">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>© 2018 powered by <a href="https://github.com/microexs"><b>Microex</b></a>.</strong>
        </footer>

    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://cdn.bootcss.com/admin-lte/2.4.2/js/adminlte.min.js"></script>
    @RenderSection("script", false)

    <!-- Optionally, you can add Slimscroll and FastClick plugins.
         Both of these plugins are recommended to enhance the
         user experience. -->

</body>
</html>
<html>
<head>
    <meta charset="UTF-8">
    <title>爱心药业管理后台</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link rel="alternate icon" type="image/png" href="~/image/favicon.png">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" rel="stylesheet">
    <style>
        body {
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>
<div class="container-fluid">
</div>
    
    
</body>
</html>